---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 6) %>
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
development:
  <<: *default
  database: gcsbrowsertest_website_development
test:
  <<: *default
  database: gcsbrowsertest_website_test
production:
  <<: *default
  database: gcsbrowsertest_website_production
  username: <%= ENV.fetch('POSTGRES_USER', '') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
